- app/containers/HomePage/index.js
- app/containers/NotFoundPage/index.js
- internals/webpack/webpack.prod.babel.js
> Change the build configuration for webpack as per dynamics

- app/components/EditQuoteGrid/index.js
- app/components/EditQuoteHeaderCard/index.js
- app/components/ProductSelectionGrid/index.js
- app/components/ProductSelectionHeaderCard/index.js
- app/components/Sidebar/index.js
- app/components/Sidebar/messages.js
- app/components/Sidebar/tests/index.test.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/index.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/index.js
- app/style.css
> ui for discount schedular, Filter sidebar and card responsive correction

- app/containers/App/constants.js
- app/containers/App/reducer.js
- app/containers/App/selectors.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/actions.js
- app/containers/EditQuotePage/constants.js
- app/containers/EditQuotePage/index.js
- app/containers/EditQuotePage/reducer.js
- app/containers/EditQuotePage/sagas.js
- app/containers/EditQuotePage/selectors.js
> code refactoring: moved api call logic to container

- app/components/EditQuoteGrid/index.js
- app/components/EditQuoteHeaderCard/index.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/actions.js
- app/containers/EditQuotePage/constants.js
- app/containers/EditQuotePage/index.js
- app/containers/EditQuotePage/reducer.js
- app/containers/EditQuotePage/selectors.js
- app/containers/ProductSelectionHeader/index.js
- app/style.css
- package.json
> Clone and delete lines

- app/components/ProductSelectionGrid/index.js
- app/components/Sidebar/index.js
- app/containers/EditQuotePage/index.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/index.js
- app/style.css
> Filter UI Correction

- app/components/ProductSelectionGrid/index.js
- app/containers/ProductSelectionHeader/actions.js
- app/containers/ProductSelectionHeader/constants.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionHeader/reducer.js
- app/containers/ProductSelectionHeader/selectors.js
- app/containers/ProductSelectionPage/actions.js
- app/containers/ProductSelectionPage/constants.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/reducer.js
- app/containers/ProductSelectionPage/selectors.js
> Filter change

- app/components/AddGroupDropdown/index.js
- app/components/AddProductsDropdown/index.js
- app/components/EditQuoteGrid/index.js
- app/containers/EditQuotePage/sagas.js
> es lint fix (some) api fix

- app/containers/App/reducer.js
- app/containers/EditQuotePage/index.js
- app/containers/EditQuotePage/selectors.js
- app/containers/PriceBook/actions.js
- app/containers/PriceBook/constants.js
- app/containers/PriceBook/index.js
- app/containers/PriceBook/messages.js
- app/containers/PriceBook/reducer.js
- app/containers/PriceBook/sagas.js
- app/containers/PriceBook/selectors.js
- app/containers/PriceBook/tests/actions.test.js
- app/containers/PriceBook/tests/index.test.js
- app/containers/PriceBook/tests/reducer.test.js
- app/containers/PriceBook/tests/sagas.test.js
- app/containers/PriceBook/tests/selectors.test.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/selectors.js
- app/routes.js
> Price book UI

- app/containers/ProductSelectionPage/actions.js
- app/containers/ProductSelectionPage/constants.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/reducer.js
> issue fix for ProductSelectionPage

- app/app.js
- app/components/ProductSelectionGrid/index.js
- app/components/Sidebar/index.js
- app/containers/App/actions.js
- app/containers/App/index.js
- app/containers/App/reducer.js
- app/containers/App/sagas.js
- app/containers/App/selectors.js
- app/containers/EditQuoteHeader/sagas.js
- app/containers/EditQuotePage/actions.js
- app/containers/EditQuotePage/constants.js
- app/containers/EditQuotePage/index.js
- app/containers/EditQuotePage/reducer.js
- app/containers/EditQuotePage/sagas.js
- app/containers/EditQuotePage/selectors.js
- app/containers/ProductSelectionPage/index.js
- app/routes.js
> Global state issue

- app/components/ProductSelectionGrid/index.js
- app/containers/App/actions.js
- app/containers/App/constants.js
- app/containers/App/reducer.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/selectors.js
> Add Products page

- app/components/EditQuoteGrid/index.js
- app/components/ProductSelectionGrid/index.js
- app/containers/App/constants.js
- app/containers/App/sagas.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/reducer.js
- app/containers/ProductSelectionPage/sagas.js
- app/containers/ProductSelectionPage/selectors.js
- app/style.css
- server/productRoutes.js
> issues resoultion from crm

- app/components/EditQuoteHeaderCard/index.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/index.js
- app/containers/ProductSelectionHeader/index.js
- package.json
> Full screen and save data

- app/components/ReconfigureFeaturePanel/index.js
- app/components/ReconfigureFeaturePanel/messages.js
- app/components/ReconfigureFeaturePanel/tests/index.test.js
- app/components/ReconfigureGrid/index.js
- app/components/ReconfigureProductTab/index.js
- app/components/ReconfigureProductTab/messages.js
- app/components/ReconfigureProductTab/tests/index.test.js
- app/containers/ReConfigureProducts/index.js
- app/style.css
> Reconfigure lines functionality

- app/components/EditQuoteGrid/index.js
- app/components/EditQuoteHeaderCard/index.js
- app/containers/App/actions.js
- app/containers/App/constants.js
- app/containers/App/reducer.js
- app/containers/App/sagas.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/index.js
- app/containers/GroupQuote/index.js
- app/containers/ProductSelectionPage/index.js
- app/style.css
> Delete line, clone line, Ungroup group in groups page

- app/components/AddConfigureProductGrid/index.js
- app/components/AddConfigureProductGrid/messages.js
- app/components/AddConfigureProductGrid/tests/index.test.js
- app/components/AddConfigureProductHeader/index.js
- app/components/AddConfigureProductHeader/messages.js
- app/components/AddConfigureProductHeader/tests/index.test.js
- app/components/ReconfigureFeaturePanel/index.js
- app/containers/AddConfigureProducts/actions.js
- app/containers/AddConfigureProducts/constants.js
- app/containers/AddConfigureProducts/index.js
- app/containers/AddConfigureProducts/messages.js
- app/containers/AddConfigureProducts/reducer.js
- app/containers/AddConfigureProducts/sagas.js
- app/containers/AddConfigureProducts/selectors.js
- app/containers/AddConfigureProducts/tests/actions.test.js
- app/containers/AddConfigureProducts/tests/index.test.js
- app/containers/AddConfigureProducts/tests/reducer.test.js
- app/containers/AddConfigureProducts/tests/sagas.test.js
- app/containers/AddConfigureProducts/tests/selectors.test.js
- app/containers/EditQuotePage/selectors.js
- app/containers/ReConfigureProducts/index.js
- app/routes.js
- app/style.css
> Implemented UI for AddOptions on configureProduct.

- app/components/EditQuoteGrid/index.js
- app/components/EditQuoteHeaderCard/index.js
- app/components/ProductSelectionGrid/index.js
- app/components/SegmentSubComponent/index.js
- app/components/SegmentSubComponent/messages.js
- app/components/SegmentSubComponent/tests/index.test.js
- app/components/SegmentedEditQuoteGrid/index.js
- app/containers/App/sagas.js
- app/containers/EditQuotePage/index.js
- app/containers/GroupQuote/index.js
- app/containers/SegmentedQuote/index.js
- app/style.css
> Segment desegment functional sub group open

- app/routes.js
> Fixed app load URL issue

- app/components/EditQuoteGrid/index.js
- app/components/SegmentSubComponent/index.js
- app/components/SegmentedEditQuoteGrid/index.js
> Chaitanya required changes

- app/containers/App/actions.js
- app/containers/App/index.js
- app/containers/App/sagas.js
- app/containers/EditQuoteHeader/index.js
- app/containers/GroupQuote/index.js
- app/containers/ProductSelectionPage/actions.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/sagas.js
- server/productRoutes.js
> api changes

- app/components/ReconfigureGrid/index.js
> Updated validate and format method of reconfigureGrid.

- app/components/CustomSegmentsModal/index.js
- app/components/EditQuoteGrid/index.js
- app/containers/EditQuotePage/index.js
- app/style.css
> Css Changes

- app/components/CustomSegmentsModal/index.js
- app/containers/App/reducer.js
- app/containers/EditQuotePage/reducer.js
- app/containers/ProductSelectionPage/reducer.js
- app/containers/ProductSelectionPage/sagas.js
- app/style.css
- package.json
- server/productRoutes.js
> Updated Date-picker  of custom Segments modal.

- app/containers/App/sagas.js
- server/quoteRoutes.js
> API NAME CHANGE

- app/containers/EditQuotePage/index.js
> Minor change

- app/containers/App/reducer.js
- app/containers/EditQuotePage/sagas.js
- app/containers/ProductSelectionPage/sagas.js
- app/routes.js
- app/style.css
- server/quoteRoutes.js
> Error message

- app/containers/EditQuotePage/sagas.js
- app/containers/ProductSelectionPage/sagas.js
- app/routes.js
> Added errors and routes

- app/components/AddConfigureProductHeader/index.js
- app/components/CustomSegmentsModal/index.js
- app/components/ReconfigureFeaturePanel/index.js
- app/components/ReconfigureProductTab/index.js
- app/containers/AddConfigureProducts/index.js
- app/containers/AddConfigureProducts/reducer.js
- app/containers/AddConfigureProducts/sagas.js
- app/containers/EditQuotePage/sagas.js
- app/containers/ReConfigureProducts/actions.js
- app/containers/ReConfigureProducts/constants.js
- app/containers/ReConfigureProducts/index.js
- app/containers/ReConfigureProducts/reducer.js
- app/containers/ReConfigureProducts/sagas.js
> Updated Sagas and AddConfigurationProduct route.

- app/containers/App/index.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/sagas.js
> APi change

- app/routes.js
> Language change fix

- app/components/AddConfigureProductHeader/index.js
- app/components/EditQuoteGrid/index.js
- app/components/ReconfigureProductHeader/index.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/index.js
- app/containers/PriceBook/index.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/index.js
- app/style.css
> Header Change name

- app/containers/App/reducer.js
> Error change

- app/components/EditQuoteGrid/index.js
- app/components/SegmentSubComponent/index.js
> Edit change on icon click

- app/components/ProductSelectionGrid/index.js
- app/containers/App/index.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuoteHeader/selectors.js
- app/containers/EditQuotePage/index.js
- app/containers/EditQuotePage/selectors.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/sagas.js
- app/containers/ProductSelectionPage/selectors.js
- app/style.css
> Language change, css and saaga modify

- app/routes.js
> route change

- app/containers/EditQuoteHeader/index.js
- app/containers/GroupQuote/index.js
- app/containers/ProductSelectionPage/actions.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/sagas.js
> Updated Product api call  with QuoteId.

- app/containers/ReConfigureProducts/index.js
> Updated route.

- app/components/DiscountScheduleEditor/index.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/index.js
- app/containers/SegmentedQuote/index.js
> Bug resolve

- app/components/SegmentedEditQuoteGrid/index.js
> Segment total change

- app/components/ReconfigureFeaturePanel/index.js
- app/containers/App/actions.js
- app/containers/App/constants.js
- app/containers/App/reducer.js
- app/containers/ReConfigureProducts/index.js
- app/containers/ReConfigureProducts/reducer.js
- app/containers/ReConfigureProducts/sagas.js
- app/style.css
> Updated save Reconfiguration  to display Error Messages.

- app/components/SegmentSubComponent/index.js
- app/containers/App/constants.js
- app/containers/EditQuotePage/index.js
- app/containers/GroupQuote/index.js
- app/containers/SegmentedQuote/index.js
- server/quoteRoutes.js
> Bug resole navigation

- app/components/SegmentSubComponent/index.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/index.js
- app/containers/GroupQuote/index.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/index.js
> location changes

- app/containers/App/sagas.js
- app/containers/EditQuoteHeader/index.js
> Bug resolve nav

- app/components/EditQuoteGrid/index.js
- app/components/ReconfigureFeaturePanel/index.js
- app/components/ReconfigureGrid/index.js
- app/components/ReconfigureProductHeader/index.js
- app/components/SegmentedEditQuoteGrid/index.js
- app/containers/EditQuotePage/index.js
- app/containers/GroupQuote/index.js
- app/containers/ReConfigureProducts/actions.js
- app/containers/ReConfigureProducts/index.js
- app/containers/ReConfigureProducts/reducer.js
- app/containers/ReConfigureProducts/sagas.js
- app/containers/SegmentedQuote/index.js
> Updated EditQuote Route and reconfigurationGrid.

- app/components/ProductSelectionGrid/index.js
- app/components/SegmentSubComponent/index.js
- app/containers/App/index.js
- app/containers/App/sagas.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/index.js
- app/containers/EditQuotePage/sagas.js
- app/containers/GroupQuote/index.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/sagas.js
- app/containers/SegmentedQuote/index.js
- server/quoteRoutes.js
> forceSave to is force save, lin fixes

- app/components/AddConfigureProductGrid/index.js
- app/components/ReconfigureGrid/index.js
- app/containers/EditQuoteHeader/index.js
- app/containers/ProductSelectionHeader/index.js
> Minor changes, remove language

- app/components/AddConfigureProductHeader/index.js
- app/components/ReconfigureProductHeader/index.js
- app/containers/App/actions.js
- app/containers/App/constants.js
- app/containers/App/reducer.js
- app/containers/ReConfigureProducts/index.js
- app/containers/ReConfigureProducts/sagas.js
> Updated Save Configuration.

- app/components/EditQuoteGrid/index.js
- app/components/SegmentSubComponent/index.js
- server/quoteRoutes.js
> add. discount bug

- app/containers/App/sagas.js
- app/containers/EditQuoteHeader/index.js
> cancel button

- app/containers/GroupQuote/index.js
> Uncommented subscription term

- app/containers/GroupQuote/index.js
> Commented optional

- app/containers/EditQuoteHeader/index.js
> Url bug resolve

- app/containers/GroupQuote/index.js
- app/containers/ProductSelectionPage/index.js
> NAv bug resolve

- app/components/SegmentedEditQuoteGrid/index.js
- app/containers/App/sagas.js
- app/containers/EditQuoteHeader/index.js
- app/containers/GroupQuote/index.js
> Remove console

- app/containers/SegmentedQuote/index.js
- app/containers/SegmentedQuote/messages.js
- app/translations/en.json
- server/quoteRoutes.js
> Quater to Quarterly

- app/style.css
> Loader change

- app/components/EditQuoteGrid/index.js
- app/components/EditQuoteHeaderCard/index.js
- app/components/ProductSelectionGrid/index.js
- app/components/ReconfigureGrid/index.js
- app/components/SegmentSubComponent/index.js
- app/components/SegmentedEditQuoteGrid/index.js
- app/containers/EditQuotePage/index.js
- app/containers/GroupQuote/index.js
- server/quoteRoutes.js
> DecimalSupport integrated

- app/components/CustomSegmentsModal/index.js
- app/containers/AddConfigureProducts/reducer.js
- app/containers/App/reducer.js
- app/containers/EditQuotePage/sagas.js
- app/containers/ProductSelectionPage/sagas.js
- app/containers/ReConfigureProducts/reducer.js
> Toaster from centre to left

- app/containers/EditQuoteHeader/index.js
> Hide clone line button

- app/containers/ProductSelectionPage/sagas.js
- app/style.css
> Bug resolve buffer

- app/components/ReconfigureFeaturePanel/index.js
- app/components/ReconfigureGrid/index.js
- app/components/ReconfigureProductTab/index.js
- app/containers/AddConfigureProducts/index.js
- app/style.css
> Updated UI of reconfiguration and addConfiguration.

- app/containers/AddConfigureProducts/reducer.js
- app/containers/App/reducer.js
- app/containers/ReConfigureProducts/reducer.js
- app/style.css
> Error toaster bug

- app/components/ProductSelectionHeaderCard/index.js
- app/components/ReconfigureProductHeaderCard/index.js
> Remove icons from headers

- app/components/ReconfigureFeaturePanel/index.js
> Update min-Max validation.

- app/components/ReconfigureProductHeader/index.js
- app/components/ReconfigureProductTab/index.js
- app/style.css
> Bug Fixed: Scrollbar missing for Configure product grid.

- app/components/CustomSegmentsModal/index.js
- app/containers/EditQuotePage/reducer.js
> Updated Custom Segments with OneTime.

- app/containers/GroupQuote/index.js
- app/style.css
> Group description change

- app/components/CustomSegmentsModal/index.js
- app/containers/AddConfigureProducts/reducer.js
- app/containers/App/reducer.js
- app/containers/EditQuoteHeader/index.js
- app/containers/EditQuotePage/index.js
- app/containers/GroupQuote/index.js
- app/containers/ReConfigureProducts/reducer.js
- app/style.css
> Bugs Resolve

- app/components/ReconfigureGrid/index.js
> Padding issue

- app/containers/EditQuotePage/index.js
- app/containers/GroupQuote/index.js
- server/quoteRoutes.js
> bugs resolution

- app/components/SearchProductAutocomplete/index.js
- app/containers/GroupQuote/index.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/index.js
- app/style.css
- server/productRoutes.js
> UI changes

- app/components/SearchProductAutocomplete/index.js
> Search bug

- app/components/SegmentSubComponent/index.js
- app/components/SegmentedEditQuoteGrid/index.js
- app/style.css
> One Time column change

- app/components/CustomSegmentsModal/index.js
- app/components/SegmentSubComponent/index.js
- app/components/SegmentedEditQuoteGrid/index.js
- app/containers/EditQuotePage/reducer.js
> One time to OneTime

- app/containers/ProductSelectionPage/index.js
- app/style.css
> Fixed: Toast text overlaping issue

- app/containers/SegmentedQuote/index.js
> Updated Segemnted Quote with toggleSuggestionStatus function

- app/components/EditQuoteGrid/index.js
- app/components/ReconfigureProductTab/index.js
- app/components/SegmentedEditQuoteGrid/index.js
- app/components/SuggestionProductPanel/index.js
- app/containers/AddConfigureProducts/index.js
- app/containers/EditQuotePage/index.js
- app/containers/SegmentedQuote/index.js
- app/containers/SuggestionPage/index.js
- app/containers/SuggestionPage/sagas.js
- app/index.html
- app/style.css
> Implemented accordian on Suggestion Page.

- app/routes.js
> Updated Suggestion route to fix execution of suggestion method twice on cancel.

- app/components/AddConfigureProductGrid/index.js
- app/components/ReconfigureGrid/index.js
- app/components/SuggestionProductGrid/index.js
- app/containers/SegmentedQuote/index.js
- app/containers/SuggestionPage/reducer.js
> Updated Suggestion reducer to handel duplicate products.

- app/containers/ReConfigureProducts/reducer.js
> Updated Reconfiguration reducer to avoid applying dependent and exclusion rule on required product.

- app/components/GuidedSellingModal/index.js
- app/containers/ProductSelectionPage/reducer.js
>  Implemented dynamic control rendering for guided selling

- app/components/ProductSelectionGrid/index.js
- app/containers/ProductSelectionPage/index.js
- app/style.css
> Implemented modal, added undefined ckeck and css

- app/components/ProductDetails/index.js
- package.json
> Removed react html parser dependency and import

- app/components/GuidedSellingModal/index.js
>  Completed all controls except range for guided selling

- app/style.css
> For some UI changes

- app/style.css
> UI css changes

- app/containers/ReConfigureProducts/sagas.js
> Fixed buffer overflow issue

- app/components/ReconfigureFeaturePanel/index.js
- app/style.css
> Implemented Accordian On reconfiguration.

- app/components/ProductDetails/index.js
- app/style.css
> For Product Modal UI changes

- app/components/GuidedSellingModal/index.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/actions.js
- app/containers/ProductSelectionPage/constants.js
- app/containers/ProductSelectionPage/index.js
- app/containers/ProductSelectionPage/reducer.js
- app/containers/ProductSelectionPage/sagas.js
> Completed filter products according to guided selling modal

- app/components/EditQuoteGrid/index.js
- app/components/SegmentSubComponent/index.js
- app/components/SegmentedEditQuoteGrid/index.js
- app/containers/App/reducer.js
> changed segment name to columnName, added suggestion icon and showed percent symbol on partner discount column

- app/style.css
> Some UI changes

- app/components/ProductDetails/index.js
- app/style.css
> For Product Modal UI

- app/components/CustomSegmentsModal/index.js
- app/containers/ReConfigureProducts/sagas.js
> Fixed column name issue and added error messages

- app/components/ProductDetails/index.js
- app/components/ProductSelectionGrid/index.js
- app/containers/ReConfigureProducts/sagas.js
> Implemented to show product code and product family, conditional link on product name and fixed errors

- app/components/EditQuoteGrid/index.js
- app/components/ProductDetails/index.js
- app/components/SegmentedEditQuoteGrid/index.js
> Implemented conditional based link showing on product name

- app/components/EditQuoteGrid/index.js
> Fixed product code rendering issue

- app/style.css
> For UI corrections for product modal

- app/components/CustomSegmentsModal/index.js
- app/containers/AddConfigureProducts/index.js
- app/containers/App/sagas.js
> Fixed alert continue issue and removed comments

- app/components/ReconfigureProductTab/index.js
- app/containers/ProductSelectionHeader/index.js
- app/containers/ProductSelectionPage/actions.js
- app/containers/ProductSelectionPage/constants.js
- app/containers/ProductSelectionPage/reducer.js
- app/containers/ProductSelectionPage/sagas.js
- app/containers/ReConfigureProducts/index.js
- app/containers/ReConfigureProducts/selectors.js
>  Fixed the issue related to multiple popup shown for Guided Selling Modal

- app/containers/ReConfigureProducts/reducer.js
> implemented optionline visibility

- app/components/EditQuoteGrid/index.js
- app/components/ReconfigureProductTab/index.js
- app/containers/ReConfigureProducts/index.js
> Implementation of validation for configure attribute inside reconfigure page

- app/components/SuggestionProductPanel/index.js
- app/containers/ReConfigureProducts/index.js
- app/index.html
- package.json
> Changed the accordian modal on Suggestion Page

- app/components/SuggestionProductPanel/index.js
- app/style.css
> For suggestion page - accordian UI

- app/containers/ReConfigureProducts/actions.js
- app/containers/ReConfigureProducts/constants.js
- app/containers/ReConfigureProducts/index.js
- app/containers/ReConfigureProducts/reducer.js
- app/containers/ReConfigureProducts/selectors.js
> Bug Fixed: #12912

- app/containers/AddConfigureProducts/sagas.js
- app/containers/App/sagas.js
- app/containers/EditQuotePage/sagas.js
- app/containers/ReConfigureProducts/sagas.js
- app/containers/SuggestionPage/sagas.js
> Resolved channel buffer overflow issue
